name: escape_wild
description: A text-based game powered by Flutter.

publish_to: 'none'

version: 1.0.0+1

environment: { sdk: '>=3.3.0 <4.0.0', flutter: ^3.19.6 }

dependencies:
  flutter:
    sdk: flutter
  # I18n
  easy_localization: ^3.0.6
  locale_names: ^1.1.1
  intl: 0.18.1

  # Basic
  collection: ^1.18.0
  json_annotation: ^4.9.0
  rettulf: ^2.0.1
  yaml: ^3.1.2
  path_provider: ^2.1.3
  event_bus: ^2.0.0
  quiver: ^3.2.1

  jconverter:
    git:
      url: https://github.com/liplum/DartPackage.git
      path: jconverter
  platform_safe_func:
    git:
      url: https://github.com/liplum/DartPackage.git
      path: platform_safe_func
  noitcelloc:
    git:
      url: https://github.com/liplum/noitcelloc.git

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2

  # UI
  flutter_layout_grid: ^2.0.6
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_sliders: ^25.1.42
  modal_bottom_sheet: ^3.0.0
  animations: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  icon_font_generator:
    git:
      url: https://github.com/Gaurav192/icon_font_generator.git
      ref: file_path_fix
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/l10n/
    - assets/vanilla/
    - assets/vanilla/l10n/
    - assets/img/
  fonts:
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Regular.ttf
    - family: IconsX
      fonts:
        - asset: assets/icons.ttf